export const countrylist = [
    { "strArea": "American", "strName": "United States of America" },
    { "strArea": "British", "strName": "England" },
    { "strArea": "Canadian", "strName": "Canada" },
    { "strArea": "Chinese", "strName": "China" },
    { "strArea": "Croatian", "strName": "Croatia" },
    { "strArea": "Dutch", "strName": "Netherlands" },
    { "strArea": "Egyptian", "strName": "Egypt" },
    { "strArea": "French", "strName": "France" },
    { "strArea": "Greek", "strName": "Greece" },
    { "strArea": "Indian", "strName": "India" },
    { "strArea": "Irish", "strName": "Ireland" },
    { "strArea": "Italian", "strName": "Italy" },
    { "strArea": "Jamaican", "strName": "Jamaica" },
    { "strArea": "Japanese", "strName": "Japan" },
    { "strArea": "Kenyan", "strName": "Kenya" },
    { "strArea": "Malaysian", "strName": "Malaysia" },
    { "strArea": "Mexican", "strName": "Mexico" },
    { "strArea": "Moroccan", "strName": "Morocco" },
    { "strArea": "Polish", "strName": "Poland" },
    { "strArea": "Portuguese", "strName": "Portugal" },
    { "strArea": "Russian", "strName": "russian federation" },
    { "strArea": "Spanish", "strName": "Spain" },
    { "strArea": "Thai", "strName": "Thailand" },
    { "strArea": "Tunisian", "strName": "Tunisia" },
    { "strArea": "Turkish", "strName": "Turkey" },
    { "strArea": "Vietnamese", "strName": "Vietnam" }
]