// export const FETCH_BY_INGREDIANT = 'FETCH_BY_INGREDIANT';
// export const FETCH_DETAIL = 'FETCH_DETAIL';
// export const FETCH_REGION = 'FETCH_REGION';
// export const FETCH_RANDOM_RECIPE = 'FETCH_RANDOM_RECIP';
// export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
// export const FETCH_CATEGORIS_FILTER = 'FETCH_CATEGORIS_FILTER';
